p3_qsort: p3_qsort.o p3_quicksort.o
	gcc -o p3_qsort p3_qsort.o p3_quicksort.o

p3_qsort.o: p3_qsort.c p3_quicksort.h
	gcc -c p3_qsort.c

p3_quicksort.o: p3_quicksort.c p3_quicksort.h
	gcc -c p3_quicksort.c